#################
### AUTOSTART ###
#################

#spotify in brave pwa
# exec-once=gio launch ~/.local/share/applications/brave-pjibgclleladliembfgfagdaldikeohf-Default.desktop 
exec-once=spotify
exec-once = waybar & hyprpaper & firefox 

exec-once =org.telegram.desktop -startintray
exec-once =org.signal.Signal -startintray
exec-once =echo $HYPRLAND_INSTANCE_SIGNATURE > /tmp/his


exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = thunar --daemons
exex-once = swaync
exec-once = kdeconnectd 
exec-once = hyprsunset
exec-once = ferdium --hidden