$mainMod = SUPER 
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$benq=DP-1
$terra=HDMI-A-1

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/look-and-feel.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/default.conf
source = ~/.config/hypr/windowrules.conf

#Workspaces Rules
workspace = 1, monitor:$benq,persistent:true
workspace = 2 , monitor:$terra,default:true,persistent:true
workspace = 3 , monitor:$terra,persistent:true



