
 
windowrule{
    name= pavu-floating
    float=yes
    match:class=org.pulseaudio.pavucontrol
    move=center 30
  size=900 500
}

windowrule {
    name=Spotify
    match:class=brave-pjibgclleladliembfgfagdaldikeohf-Default
    workspace=3 silent
   
    # float=yes
    size=1000 800
}
windowrule {
    name=discord
    match:class=discord
    workspace=3
    move=center
    # float=yes
    size=1500 1000
}

windowrule {
    name=Signal
    match:class=org.signal.Signal
    move=center
    float=yes
    size=1000 800
}

windowrule {
    name=Telegram
    match:class=org.telegram.desktop
    move=center
    float=yes
    size=1000 800
}
windowrule {
    name=firefox
    match:class=firefox
    workspace=1
    border_size=0
   
}

windowrule {
    name=baobab
    match:class=org.gnome.baobab
    float=yes   
    move=center
}